apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-tomcat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-tomcat
    spec:
      containers:
      - name: my-tomcat
        image: gengxiaofang/tomcat8_jk_test:<BUILD_TAG>
        ports:
        - containerPort: 8080
        env:
        - name: branch
          value: <BRANCH_NAME>

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat8-jk-gxf
spec:
  type: NodePort
  selector:
    app: my-tomcat
  ports:
  - name: tomcat
    port: 30005
    targetPort: 8080
    nodePort: 30006

